#!/usr/bin/env bash

# This file is part of RetroPie.
# 
# (c) Copyright 2012-2015  Florian Müller (contact@petrockblock.com)
# 
# See the LICENSE.md file at the top-level directory of this distribution and 
# at https://raw.githubusercontent.com/RetroPie/RetroPie-Setup/master/LICENSE.md
#

rp_module_id="lr-ppsspp"
rp_module_desc="PSP emu - PPSSPP"
rp_module_menus="4+"

function sources_lr-ppsspp() {
    gitPullOrClone "$md_build" https://github.com/gizmo98/ppsspp.git rpi-fix
    git submodule update --init
}

function build_lr-ppsspp() {
    make -C libretro clean
    make -C libretro platform=rpi2
    md_ret_require="$md_build/libretro/ppsspp_libretro.so"
}

function install_lr-ppsspp() {
    md_ret_files=(
        'libretro/ppsspp_libretro.so'
    )
}

function configure_lr-ppsspp() {
    mkRomDir "psp"

    delSystem "$md_id" "psp-ppsspp"
    addSystem 0 "$md_id" "psp" "$md_inst/ppsspp_libretro.so"
}
