// GLSL shader autogenerated by cg2glsl.py.
#if defined(VERTEX)

#if __VERSION__ >= 130
#define COMPAT_VARYING out
#define COMPAT_ATTRIBUTE in
#define COMPAT_TEXTURE texture
#else
#define COMPAT_VARYING varying 
#define COMPAT_ATTRIBUTE attribute 
#define COMPAT_TEXTURE texture2D
#endif

#ifdef GL_ES
#define COMPAT_PRECISION mediump
#else
#define COMPAT_PRECISION
#endif
COMPAT_VARYING     vec4 _t1;
COMPAT_VARYING     vec2 _texCoord1;
COMPAT_VARYING     vec4 _color1;
COMPAT_VARYING     vec4 _position1;
COMPAT_VARYING     float _frame_rotation;
struct input_dummy {
    vec2 _video_size;
    vec2 _texture_size;
    vec2 _output_dummy_size;
    float _frame_count;
    float _frame_direction;
    float _frame_rotation;
};
struct out_vertex {
    vec4 _position1;
    vec4 _color1;
    vec2 _texCoord1;
    vec4 _t1;
};
out_vertex _ret_0;
input_dummy _IN1;
vec4 _r0008;
COMPAT_ATTRIBUTE vec4 VertexCoord;
COMPAT_ATTRIBUTE vec4 COLOR;
COMPAT_ATTRIBUTE vec4 TexCoord;
COMPAT_VARYING vec4 COL0;
COMPAT_VARYING vec4 TEX0;
COMPAT_VARYING vec4 TEX1;
 
uniform mat4 MVPMatrix;
uniform int FrameDirection;
uniform int FrameCount;
uniform COMPAT_PRECISION vec2 OutputSize;
uniform COMPAT_PRECISION vec2 TextureSize;
uniform COMPAT_PRECISION vec2 InputSize;
void main()
{
    out_vertex _OUT;
    vec2 _ps;
    _r0008 = VertexCoord.x*MVPMatrix[0];
    _r0008 = _r0008 + VertexCoord.y*MVPMatrix[1];
    _r0008 = _r0008 + VertexCoord.z*MVPMatrix[2];
    _r0008 = _r0008 + VertexCoord.w*MVPMatrix[3];
    _ps = vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y);
    _OUT._t1.xy = vec2(_ps.x, 0.00000000E+00);
    _OUT._t1.zw = vec2(0.00000000E+00, _ps.y);
    _ret_0._position1 = _r0008;
    _ret_0._color1 = COLOR;
    _ret_0._texCoord1 = TexCoord.xy;
    _ret_0._t1 = _OUT._t1;
    gl_Position = _r0008;
    COL0 = COLOR;
    TEX0.xy = TexCoord.xy;
    TEX1 = _OUT._t1;
    return;
    COL0 = _ret_0._color1;
    TEX0.xy = _ret_0._texCoord1;
    TEX1 = _ret_0._t1;
} 
#elif defined(FRAGMENT)

#if __VERSION__ >= 130
#define COMPAT_VARYING in
#define COMPAT_TEXTURE texture
out vec4 FragColor;
#else
#define COMPAT_VARYING varying
#define FragColor gl_FragColor
#define COMPAT_TEXTURE texture2D
#endif

#ifdef GL_ES
#ifdef GL_FRAGMENT_PRECISION_HIGH
precision highp float;
#else
precision mediump float;
#endif
#define COMPAT_PRECISION mediump
#else
#define COMPAT_PRECISION
#endif
COMPAT_VARYING     vec4 _t1;
COMPAT_VARYING     vec2 _texCoord;
COMPAT_VARYING     vec4 _color;
COMPAT_VARYING     float _frame_rotation;
struct input_dummy {
    vec2 _video_size;
    vec2 _texture_size;
    vec2 _output_dummy_size;
    float _frame_count;
    float _frame_direction;
    float _frame_rotation;
};
struct out_vertex {
    vec4 _color;
    vec2 _texCoord;
    vec4 _t1;
};
vec4 _ret_0;
vec3 _TMP29;
vec3 _TMP31;
vec3 _TMP33;
vec3 _TMP35;
vec3 _TMP36;
vec3 _TMP34;
vec3 _TMP32;
vec3 _TMP30;
vec4 _TMP22;
vec4 _TMP21;
vec3 _TMP44;
vec3 _TMP42;
vec3 _TMP40;
vec3 _TMP38;
vec4 _TMP20;
vec4 _TMP19;
vec4 _TMP18;
vec4 _TMP17;
vec4 _TMP16;
vec4 _TMP15;
vec4 _TMP14;
vec4 _TMP13;
vec4 _TMP12;
vec4 _TMP11;
vec4 _TMP10;
vec4 _TMP9;
vec4 _TMP8;
vec4 _TMP7;
vec4 _TMP6;
vec4 _TMP5;
vec4 _TMP4;
vec4 _TMP3;
vec4 _TMP2;
vec4 _TMP1;
vec4 _TMP0;
uniform sampler2D Texture;
input_dummy _IN1;
vec2 _x0082;
vec2 _c0084;
vec2 _c0086;
vec2 _c0088;
vec2 _c0090;
vec2 _c0094;
vec2 _c0096;
vec2 _c0098;
vec2 _c0100;
vec2 _c0102;
vec2 _c0104;
vec2 _c0106;
vec2 _c0108;
vec2 _c0110;
vec2 _c0112;
vec2 _c0114;
vec2 _c0116;
vec2 _c0118;
vec2 _c0120;
vec2 _c0122;
vec2 _c0124;
vec3 _r0170;
vec3 _r0180;
vec3 _r0190;
vec3 _r0200;
vec3 _r0212;
vec3 _r0222;
vec3 _r0232;
vec3 _r0242;
vec3 _r0254;
vec3 _r0264;
vec3 _r0274;
vec3 _r0284;
vec3 _r0296;
vec3 _r0306;
vec3 _r0316;
vec3 _r0326;
vec3 _r0338;
vec3 _r0348;
vec3 _r0358;
vec3 _r0368;
vec3 _r0380;
vec3 _r0390;
vec3 _r0400;
vec3 _r0410;
vec3 _r0422;
vec3 _r0432;
vec3 _r0442;
vec3 _r0452;
vec3 _r0464;
vec3 _r0474;
vec3 _r0484;
vec3 _r0494;
vec3 _r0716;
vec3 _r0726;
vec3 _r0736;
vec3 _r0746;
vec3 _r0800;
vec3 _r0810;
vec3 _r0820;
vec3 _r0830;
vec3 _r0926;
vec3 _r0936;
vec3 _r0946;
vec3 _r0956;
vec3 _r0968;
vec3 _r0978;
vec3 _r0988;
vec3 _r0998;
vec4 _TMP1009;
vec4 _a1012;
vec4 _TMP1013;
vec4 _a1016;
vec4 _TMP1017;
vec4 _a1020;
vec4 _TMP1021;
vec4 _a1024;
vec4 _TMP1025;
vec4 _a1028;
vec4 _TMP1031;
vec4 _a1034;
vec4 _TMP1035;
vec4 _a1038;
vec4 _TMP1039;
vec4 _a1042;
vec4 _TMP1043;
vec4 _a1046;
vec4 _TMP1047;
vec4 _a1050;
vec4 _TMP1051;
vec4 _a1054;
vec4 _TMP1055;
vec4 _a1058;
vec4 _TMP1059;
vec4 _a1062;
vec4 _TMP1063;
vec4 _a1066;
vec4 _TMP1067;
vec4 _a1070;
vec4 _TMP1071;
vec4 _a1074;
COMPAT_VARYING vec4 TEX0;
COMPAT_VARYING vec4 TEX1;
 
uniform int FrameDirection;
uniform int FrameCount;
uniform COMPAT_PRECISION vec2 OutputSize;
uniform COMPAT_PRECISION vec2 TextureSize;
uniform COMPAT_PRECISION vec2 InputSize;
void main()
{
    bvec4 _edr;
    bvec4 _edr_left;
    bvec4 _edr_up;
    bvec4 _px;
    bvec4 _interp_restriction_lv1;
    bvec4 _interp_restriction_lv2_left;
    bvec4 _interp_restriction_lv2_up;
    bvec4 _nc;
    bvec4 _fx;
    bvec4 _fx_left;
    bvec4 _fx_up;
    vec2 _fp;
    vec4 _b2;
    vec4 _c2;
    vec4 _d2;
    vec4 _e1;
    vec4 _f1;
    vec4 _g1;
    vec4 _h1;
    vec4 _i;
    vec4 _i4;
    vec4 _i5;
    vec4 _h5;
    vec4 _f4;
    _x0082 = TEX0.xy*TextureSize;
    _fp = fract(_x0082);
    _c0084 = (TEX0.xy - TEX1.xy) - TEX1.zw;
    _TMP0 = COMPAT_TEXTURE(Texture, _c0084);
    _c0086 = TEX0.xy - TEX1.zw;
    _TMP1 = COMPAT_TEXTURE(Texture, _c0086);
    _c0088 = (TEX0.xy + TEX1.xy) - TEX1.zw;
    _TMP2 = COMPAT_TEXTURE(Texture, _c0088);
    _c0090 = TEX0.xy - TEX1.xy;
    _TMP3 = COMPAT_TEXTURE(Texture, _c0090);
    _TMP4 = COMPAT_TEXTURE(Texture, TEX0.xy);
    _c0094 = TEX0.xy + TEX1.xy;
    _TMP5 = COMPAT_TEXTURE(Texture, _c0094);
    _c0096 = (TEX0.xy - TEX1.xy) + TEX1.zw;
    _TMP6 = COMPAT_TEXTURE(Texture, _c0096);
    _c0098 = TEX0.xy + TEX1.zw;
    _TMP7 = COMPAT_TEXTURE(Texture, _c0098);
    _c0100 = TEX0.xy + TEX1.xy + TEX1.zw;
    _TMP8 = COMPAT_TEXTURE(Texture, _c0100);
    _c0102 = (TEX0.xy - TEX1.xy) - 2.00000000E+00*TEX1.zw;
    _TMP9 = COMPAT_TEXTURE(Texture, _c0102);
    _c0104 = (TEX0.xy + TEX1.xy) - 2.00000000E+00*TEX1.zw;
    _TMP10 = COMPAT_TEXTURE(Texture, _c0104);
    _c0106 = (TEX0.xy - 2.00000000E+00*TEX1.xy) - TEX1.zw;
    _TMP11 = COMPAT_TEXTURE(Texture, _c0106);
    _c0108 = (TEX0.xy - 2.00000000E+00*TEX1.xy) + TEX1.zw;
    _TMP12 = COMPAT_TEXTURE(Texture, _c0108);
    _c0110 = (TEX0.xy + 2.00000000E+00*TEX1.xy) - TEX1.zw;
    _TMP13 = COMPAT_TEXTURE(Texture, _c0110);
    _c0112 = TEX0.xy + 2.00000000E+00*TEX1.xy + TEX1.zw;
    _TMP14 = COMPAT_TEXTURE(Texture, _c0112);
    _c0114 = (TEX0.xy - TEX1.xy) + 2.00000000E+00*TEX1.zw;
    _TMP15 = COMPAT_TEXTURE(Texture, _c0114);
    _c0116 = TEX0.xy + TEX1.xy + 2.00000000E+00*TEX1.zw;
    _TMP16 = COMPAT_TEXTURE(Texture, _c0116);
    _c0118 = TEX0.xy - 2.00000000E+00*TEX1.zw;
    _TMP17 = COMPAT_TEXTURE(Texture, _c0118);
    _c0120 = TEX0.xy - 2.00000000E+00*TEX1.xy;
    _TMP18 = COMPAT_TEXTURE(Texture, _c0120);
    _c0122 = TEX0.xy + 2.00000000E+00*TEX1.zw;
    _TMP19 = COMPAT_TEXTURE(Texture, _c0122);
    _c0124 = TEX0.xy + 2.00000000E+00*TEX1.xy;
    _TMP20 = COMPAT_TEXTURE(Texture, _c0124);
    _r0170.x = dot(vec3( 1.43519993E+01, 2.81760006E+01, 5.47200012E+00), _TMP1.xyz);
    _r0170.y = dot(vec3( -1.18299997E+00, -2.31699991E+00, 3.49300003E+00), _TMP1.xyz);
    _r0170.z = dot(vec3( 2.99399996E+00, -2.50800014E+00, -4.87800002E-01), _TMP1.xyz);
    _TMP38 = abs(_r0170);
    _r0180.x = dot(vec3( 1.43519993E+01, 2.81760006E+01, 5.47200012E+00), _TMP3.xyz);
    _r0180.y = dot(vec3( -1.18299997E+00, -2.31699991E+00, 3.49300003E+00), _TMP3.xyz);
    _r0180.z = dot(vec3( 2.99399996E+00, -2.50800014E+00, -4.87800002E-01), _TMP3.xyz);
    _TMP40 = abs(_r0180);
    _r0190.x = dot(vec3( 1.43519993E+01, 2.81760006E+01, 5.47200012E+00), _TMP7.xyz);
    _r0190.y = dot(vec3( -1.18299997E+00, -2.31699991E+00, 3.49300003E+00), _TMP7.xyz);
    _r0190.z = dot(vec3( 2.99399996E+00, -2.50800014E+00, -4.87800002E-01), _TMP7.xyz);
    _TMP42 = abs(_r0190);
    _r0200.x = dot(vec3( 1.43519993E+01, 2.81760006E+01, 5.47200012E+00), _TMP5.xyz);
    _r0200.y = dot(vec3( -1.18299997E+00, -2.31699991E+00, 3.49300003E+00), _TMP5.xyz);
    _r0200.z = dot(vec3( 2.99399996E+00, -2.50800014E+00, -4.87800002E-01), _TMP5.xyz);
    _TMP44 = abs(_r0200);
    _b2 = vec4(_TMP38.x, _TMP40.x, _TMP42.x, _TMP44.x);
    _r0212.x = dot(vec3( 1.43519993E+01, 2.81760006E+01, 5.47200012E+00), _TMP2.xyz);
    _r0212.y = dot(vec3( -1.18299997E+00, -2.31699991E+00, 3.49300003E+00), _TMP2.xyz);
    _r0212.z = dot(vec3( 2.99399996E+00, -2.50800014E+00, -4.87800002E-01), _TMP2.xyz);
    _TMP38 = abs(_r0212);
    _r0222.x = dot(vec3( 1.43519993E+01, 2.81760006E+01, 5.47200012E+00), _TMP0.xyz);
    _r0222.y = dot(vec3( -1.18299997E+00, -2.31699991E+00, 3.49300003E+00), _TMP0.xyz);
    _r0222.z = dot(vec3( 2.99399996E+00, -2.50800014E+00, -4.87800002E-01), _TMP0.xyz);
    _TMP40 = abs(_r0222);
    _r0232.x = dot(vec3( 1.43519993E+01, 2.81760006E+01, 5.47200012E+00), _TMP6.xyz);
    _r0232.y = dot(vec3( -1.18299997E+00, -2.31699991E+00, 3.49300003E+00), _TMP6.xyz);
    _r0232.z = dot(vec3( 2.99399996E+00, -2.50800014E+00, -4.87800002E-01), _TMP6.xyz);
    _TMP42 = abs(_r0232);
    _r0242.x = dot(vec3( 1.43519993E+01, 2.81760006E+01, 5.47200012E+00), _TMP8.xyz);
    _r0242.y = dot(vec3( -1.18299997E+00, -2.31699991E+00, 3.49300003E+00), _TMP8.xyz);
    _r0242.z = dot(vec3( 2.99399996E+00, -2.50800014E+00, -4.87800002E-01), _TMP8.xyz);
    _TMP44 = abs(_r0242);
    _c2 = vec4(_TMP38.x, _TMP40.x, _TMP42.x, _TMP44.x);
    _r0254.x = dot(vec3( 1.43519993E+01, 2.81760006E+01, 5.47200012E+00), _TMP3.xyz);
    _r0254.y = dot(vec3( -1.18299997E+00, -2.31699991E+00, 3.49300003E+00), _TMP3.xyz);
    _r0254.z = dot(vec3( 2.99399996E+00, -2.50800014E+00, -4.87800002E-01), _TMP3.xyz);
    _TMP38 = abs(_r0254);
    _r0264.x = dot(vec3( 1.43519993E+01, 2.81760006E+01, 5.47200012E+00), _TMP7.xyz);
    _r0264.y = dot(vec3( -1.18299997E+00, -2.31699991E+00, 3.49300003E+00), _TMP7.xyz);
    _r0264.z = dot(vec3( 2.99399996E+00, -2.50800014E+00, -4.87800002E-01), _TMP7.xyz);
    _TMP40 = abs(_r0264);
    _r0274.x = dot(vec3( 1.43519993E+01, 2.81760006E+01, 5.47200012E+00), _TMP5.xyz);
    _r0274.y = dot(vec3( -1.18299997E+00, -2.31699991E+00, 3.49300003E+00), _TMP5.xyz);
    _r0274.z = dot(vec3( 2.99399996E+00, -2.50800014E+00, -4.87800002E-01), _TMP5.xyz);
    _TMP42 = abs(_r0274);
    _r0284.x = dot(vec3( 1.43519993E+01, 2.81760006E+01, 5.47200012E+00), _TMP1.xyz);
    _r0284.y = dot(vec3( -1.18299997E+00, -2.31699991E+00, 3.49300003E+00), _TMP1.xyz);
    _r0284.z = dot(vec3( 2.99399996E+00, -2.50800014E+00, -4.87800002E-01), _TMP1.xyz);
    _TMP44 = abs(_r0284);
    _d2 = vec4(_TMP38.x, _TMP40.x, _TMP42.x, _TMP44.x);
    _r0296.x = dot(vec3( 1.43519993E+01, 2.81760006E+01, 5.47200012E+00), _TMP4.xyz);
    _r0296.y = dot(vec3( -1.18299997E+00, -2.31699991E+00, 3.49300003E+00), _TMP4.xyz);
    _r0296.z = dot(vec3( 2.99399996E+00, -2.50800014E+00, -4.87800002E-01), _TMP4.xyz);
    _TMP38 = abs(_r0296);
    _r0306.x = dot(vec3( 1.43519993E+01, 2.81760006E+01, 5.47200012E+00), _TMP4.xyz);
    _r0306.y = dot(vec3( -1.18299997E+00, -2.31699991E+00, 3.49300003E+00), _TMP4.xyz);
    _r0306.z = dot(vec3( 2.99399996E+00, -2.50800014E+00, -4.87800002E-01), _TMP4.xyz);
    _TMP40 = abs(_r0306);
    _r0316.x = dot(vec3( 1.43519993E+01, 2.81760006E+01, 5.47200012E+00), _TMP4.xyz);
    _r0316.y = dot(vec3( -1.18299997E+00, -2.31699991E+00, 3.49300003E+00), _TMP4.xyz);
    _r0316.z = dot(vec3( 2.99399996E+00, -2.50800014E+00, -4.87800002E-01), _TMP4.xyz);
    _TMP42 = abs(_r0316);
    _r0326.x = dot(vec3( 1.43519993E+01, 2.81760006E+01, 5.47200012E+00), _TMP4.xyz);
    _r0326.y = dot(vec3( -1.18299997E+00, -2.31699991E+00, 3.49300003E+00), _TMP4.xyz);
    _r0326.z = dot(vec3( 2.99399996E+00, -2.50800014E+00, -4.87800002E-01), _TMP4.xyz);
    _TMP44 = abs(_r0326);
    _e1 = vec4(_TMP38.x, _TMP40.x, _TMP42.x, _TMP44.x);
    _r0338.x = dot(vec3( 1.43519993E+01, 2.81760006E+01, 5.47200012E+00), _TMP5.xyz);
    _r0338.y = dot(vec3( -1.18299997E+00, -2.31699991E+00, 3.49300003E+00), _TMP5.xyz);
    _r0338.z = dot(vec3( 2.99399996E+00, -2.50800014E+00, -4.87800002E-01), _TMP5.xyz);
    _TMP38 = abs(_r0338);
    _r0348.x = dot(vec3( 1.43519993E+01, 2.81760006E+01, 5.47200012E+00), _TMP1.xyz);
    _r0348.y = dot(vec3( -1.18299997E+00, -2.31699991E+00, 3.49300003E+00), _TMP1.xyz);
    _r0348.z = dot(vec3( 2.99399996E+00, -2.50800014E+00, -4.87800002E-01), _TMP1.xyz);
    _TMP40 = abs(_r0348);
    _r0358.x = dot(vec3( 1.43519993E+01, 2.81760006E+01, 5.47200012E+00), _TMP3.xyz);
    _r0358.y = dot(vec3( -1.18299997E+00, -2.31699991E+00, 3.49300003E+00), _TMP3.xyz);
    _r0358.z = dot(vec3( 2.99399996E+00, -2.50800014E+00, -4.87800002E-01), _TMP3.xyz);
    _TMP42 = abs(_r0358);
    _r0368.x = dot(vec3( 1.43519993E+01, 2.81760006E+01, 5.47200012E+00), _TMP7.xyz);
    _r0368.y = dot(vec3( -1.18299997E+00, -2.31699991E+00, 3.49300003E+00), _TMP7.xyz);
    _r0368.z = dot(vec3( 2.99399996E+00, -2.50800014E+00, -4.87800002E-01), _TMP7.xyz);
    _TMP44 = abs(_r0368);
    _f1 = vec4(_TMP38.x, _TMP40.x, _TMP42.x, _TMP44.x);
    _r0380.x = dot(vec3( 1.43519993E+01, 2.81760006E+01, 5.47200012E+00), _TMP6.xyz);
    _r0380.y = dot(vec3( -1.18299997E+00, -2.31699991E+00, 3.49300003E+00), _TMP6.xyz);
    _r0380.z = dot(vec3( 2.99399996E+00, -2.50800014E+00, -4.87800002E-01), _TMP6.xyz);
    _TMP38 = abs(_r0380);
    _r0390.x = dot(vec3( 1.43519993E+01, 2.81760006E+01, 5.47200012E+00), _TMP8.xyz);
    _r0390.y = dot(vec3( -1.18299997E+00, -2.31699991E+00, 3.49300003E+00), _TMP8.xyz);
    _r0390.z = dot(vec3( 2.99399996E+00, -2.50800014E+00, -4.87800002E-01), _TMP8.xyz);
    _TMP40 = abs(_r0390);
    _r0400.x = dot(vec3( 1.43519993E+01, 2.81760006E+01, 5.47200012E+00), _TMP2.xyz);
    _r0400.y = dot(vec3( -1.18299997E+00, -2.31699991E+00, 3.49300003E+00), _TMP2.xyz);
    _r0400.z = dot(vec3( 2.99399996E+00, -2.50800014E+00, -4.87800002E-01), _TMP2.xyz);
    _TMP42 = abs(_r0400);
    _r0410.x = dot(vec3( 1.43519993E+01, 2.81760006E+01, 5.47200012E+00), _TMP0.xyz);
    _r0410.y = dot(vec3( -1.18299997E+00, -2.31699991E+00, 3.49300003E+00), _TMP0.xyz);
    _r0410.z = dot(vec3( 2.99399996E+00, -2.50800014E+00, -4.87800002E-01), _TMP0.xyz);
    _TMP44 = abs(_r0410);
    _g1 = vec4(_TMP38.x, _TMP40.x, _TMP42.x, _TMP44.x);
    _r0422.x = dot(vec3( 1.43519993E+01, 2.81760006E+01, 5.47200012E+00), _TMP7.xyz);
    _r0422.y = dot(vec3( -1.18299997E+00, -2.31699991E+00, 3.49300003E+00), _TMP7.xyz);
    _r0422.z = dot(vec3( 2.99399996E+00, -2.50800014E+00, -4.87800002E-01), _TMP7.xyz);
    _TMP38 = abs(_r0422);
    _r0432.x = dot(vec3( 1.43519993E+01, 2.81760006E+01, 5.47200012E+00), _TMP5.xyz);
    _r0432.y = dot(vec3( -1.18299997E+00, -2.31699991E+00, 3.49300003E+00), _TMP5.xyz);
    _r0432.z = dot(vec3( 2.99399996E+00, -2.50800014E+00, -4.87800002E-01), _TMP5.xyz);
    _TMP40 = abs(_r0432);
    _r0442.x = dot(vec3( 1.43519993E+01, 2.81760006E+01, 5.47200012E+00), _TMP1.xyz);
    _r0442.y = dot(vec3( -1.18299997E+00, -2.31699991E+00, 3.49300003E+00), _TMP1.xyz);
    _r0442.z = dot(vec3( 2.99399996E+00, -2.50800014E+00, -4.87800002E-01), _TMP1.xyz);
    _TMP42 = abs(_r0442);
    _r0452.x = dot(vec3( 1.43519993E+01, 2.81760006E+01, 5.47200012E+00), _TMP3.xyz);
    _r0452.y = dot(vec3( -1.18299997E+00, -2.31699991E+00, 3.49300003E+00), _TMP3.xyz);
    _r0452.z = dot(vec3( 2.99399996E+00, -2.50800014E+00, -4.87800002E-01), _TMP3.xyz);
    _TMP44 = abs(_r0452);
    _h1 = vec4(_TMP38.x, _TMP40.x, _TMP42.x, _TMP44.x);
    _r0464.x = dot(vec3( 1.43519993E+01, 2.81760006E+01, 5.47200012E+00), _TMP8.xyz);
    _r0464.y = dot(vec3( -1.18299997E+00, -2.31699991E+00, 3.49300003E+00), _TMP8.xyz);
    _r0464.z = dot(vec3( 2.99399996E+00, -2.50800014E+00, -4.87800002E-01), _TMP8.xyz);
    _TMP38 = abs(_r0464);
    _r0474.x = dot(vec3( 1.43519993E+01, 2.81760006E+01, 5.47200012E+00), _TMP2.xyz);
    _r0474.y = dot(vec3( -1.18299997E+00, -2.31699991E+00, 3.49300003E+00), _TMP2.xyz);
    _r0474.z = dot(vec3( 2.99399996E+00, -2.50800014E+00, -4.87800002E-01), _TMP2.xyz);
    _TMP40 = abs(_r0474);
    _r0484.x = dot(vec3( 1.43519993E+01, 2.81760006E+01, 5.47200012E+00), _TMP0.xyz);
    _r0484.y = dot(vec3( -1.18299997E+00, -2.31699991E+00, 3.49300003E+00), _TMP0.xyz);
    _r0484.z = dot(vec3( 2.99399996E+00, -2.50800014E+00, -4.87800002E-01), _TMP0.xyz);
    _TMP42 = abs(_r0484);
    _r0494.x = dot(vec3( 1.43519993E+01, 2.81760006E+01, 5.47200012E+00), _TMP6.xyz);
    _r0494.y = dot(vec3( -1.18299997E+00, -2.31699991E+00, 3.49300003E+00), _TMP6.xyz);
    _r0494.z = dot(vec3( 2.99399996E+00, -2.50800014E+00, -4.87800002E-01), _TMP6.xyz);
    _TMP44 = abs(_r0494);
    _i = vec4(_TMP38.x, _TMP40.x, _TMP42.x, _TMP44.x);
    _r0716.x = dot(vec3( 1.43519993E+01, 2.81760006E+01, 5.47200012E+00), _TMP14.xyz);
    _r0716.y = dot(vec3( -1.18299997E+00, -2.31699991E+00, 3.49300003E+00), _TMP14.xyz);
    _r0716.z = dot(vec3( 2.99399996E+00, -2.50800014E+00, -4.87800002E-01), _TMP14.xyz);
    _TMP38 = abs(_r0716);
    _r0726.x = dot(vec3( 1.43519993E+01, 2.81760006E+01, 5.47200012E+00), _TMP10.xyz);
    _r0726.y = dot(vec3( -1.18299997E+00, -2.31699991E+00, 3.49300003E+00), _TMP10.xyz);
    _r0726.z = dot(vec3( 2.99399996E+00, -2.50800014E+00, -4.87800002E-01), _TMP10.xyz);
    _TMP40 = abs(_r0726);
    _r0736.x = dot(vec3( 1.43519993E+01, 2.81760006E+01, 5.47200012E+00), _TMP11.xyz);
    _r0736.y = dot(vec3( -1.18299997E+00, -2.31699991E+00, 3.49300003E+00), _TMP11.xyz);
    _r0736.z = dot(vec3( 2.99399996E+00, -2.50800014E+00, -4.87800002E-01), _TMP11.xyz);
    _TMP42 = abs(_r0736);
    _r0746.x = dot(vec3( 1.43519993E+01, 2.81760006E+01, 5.47200012E+00), _TMP15.xyz);
    _r0746.y = dot(vec3( -1.18299997E+00, -2.31699991E+00, 3.49300003E+00), _TMP15.xyz);
    _r0746.z = dot(vec3( 2.99399996E+00, -2.50800014E+00, -4.87800002E-01), _TMP15.xyz);
    _TMP44 = abs(_r0746);
    _i4 = vec4(_TMP38.x, _TMP40.x, _TMP42.x, _TMP44.x);
    _r0800.x = dot(vec3( 1.43519993E+01, 2.81760006E+01, 5.47200012E+00), _TMP16.xyz);
    _r0800.y = dot(vec3( -1.18299997E+00, -2.31699991E+00, 3.49300003E+00), _TMP16.xyz);
    _r0800.z = dot(vec3( 2.99399996E+00, -2.50800014E+00, -4.87800002E-01), _TMP16.xyz);
    _TMP38 = abs(_r0800);
    _r0810.x = dot(vec3( 1.43519993E+01, 2.81760006E+01, 5.47200012E+00), _TMP13.xyz);
    _r0810.y = dot(vec3( -1.18299997E+00, -2.31699991E+00, 3.49300003E+00), _TMP13.xyz);
    _r0810.z = dot(vec3( 2.99399996E+00, -2.50800014E+00, -4.87800002E-01), _TMP13.xyz);
    _TMP40 = abs(_r0810);
    _r0820.x = dot(vec3( 1.43519993E+01, 2.81760006E+01, 5.47200012E+00), _TMP9.xyz);
    _r0820.y = dot(vec3( -1.18299997E+00, -2.31699991E+00, 3.49300003E+00), _TMP9.xyz);
    _r0820.z = dot(vec3( 2.99399996E+00, -2.50800014E+00, -4.87800002E-01), _TMP9.xyz);
    _TMP42 = abs(_r0820);
    _r0830.x = dot(vec3( 1.43519993E+01, 2.81760006E+01, 5.47200012E+00), _TMP12.xyz);
    _r0830.y = dot(vec3( -1.18299997E+00, -2.31699991E+00, 3.49300003E+00), _TMP12.xyz);
    _r0830.z = dot(vec3( 2.99399996E+00, -2.50800014E+00, -4.87800002E-01), _TMP12.xyz);
    _TMP44 = abs(_r0830);
    _i5 = vec4(_TMP38.x, _TMP40.x, _TMP42.x, _TMP44.x);
    _r0926.x = dot(vec3( 1.43519993E+01, 2.81760006E+01, 5.47200012E+00), _TMP19.xyz);
    _r0926.y = dot(vec3( -1.18299997E+00, -2.31699991E+00, 3.49300003E+00), _TMP19.xyz);
    _r0926.z = dot(vec3( 2.99399996E+00, -2.50800014E+00, -4.87800002E-01), _TMP19.xyz);
    _TMP38 = abs(_r0926);
    _r0936.x = dot(vec3( 1.43519993E+01, 2.81760006E+01, 5.47200012E+00), _TMP20.xyz);
    _r0936.y = dot(vec3( -1.18299997E+00, -2.31699991E+00, 3.49300003E+00), _TMP20.xyz);
    _r0936.z = dot(vec3( 2.99399996E+00, -2.50800014E+00, -4.87800002E-01), _TMP20.xyz);
    _TMP40 = abs(_r0936);
    _r0946.x = dot(vec3( 1.43519993E+01, 2.81760006E+01, 5.47200012E+00), _TMP17.xyz);
    _r0946.y = dot(vec3( -1.18299997E+00, -2.31699991E+00, 3.49300003E+00), _TMP17.xyz);
    _r0946.z = dot(vec3( 2.99399996E+00, -2.50800014E+00, -4.87800002E-01), _TMP17.xyz);
    _TMP42 = abs(_r0946);
    _r0956.x = dot(vec3( 1.43519993E+01, 2.81760006E+01, 5.47200012E+00), _TMP18.xyz);
    _r0956.y = dot(vec3( -1.18299997E+00, -2.31699991E+00, 3.49300003E+00), _TMP18.xyz);
    _r0956.z = dot(vec3( 2.99399996E+00, -2.50800014E+00, -4.87800002E-01), _TMP18.xyz);
    _TMP44 = abs(_r0956);
    _h5 = vec4(_TMP38.x, _TMP40.x, _TMP42.x, _TMP44.x);
    _r0968.x = dot(vec3( 1.43519993E+01, 2.81760006E+01, 5.47200012E+00), _TMP20.xyz);
    _r0968.y = dot(vec3( -1.18299997E+00, -2.31699991E+00, 3.49300003E+00), _TMP20.xyz);
    _r0968.z = dot(vec3( 2.99399996E+00, -2.50800014E+00, -4.87800002E-01), _TMP20.xyz);
    _TMP38 = abs(_r0968);
    _r0978.x = dot(vec3( 1.43519993E+01, 2.81760006E+01, 5.47200012E+00), _TMP17.xyz);
    _r0978.y = dot(vec3( -1.18299997E+00, -2.31699991E+00, 3.49300003E+00), _TMP17.xyz);
    _r0978.z = dot(vec3( 2.99399996E+00, -2.50800014E+00, -4.87800002E-01), _TMP17.xyz);
    _TMP40 = abs(_r0978);
    _r0988.x = dot(vec3( 1.43519993E+01, 2.81760006E+01, 5.47200012E+00), _TMP18.xyz);
    _r0988.y = dot(vec3( -1.18299997E+00, -2.31699991E+00, 3.49300003E+00), _TMP18.xyz);
    _r0988.z = dot(vec3( 2.99399996E+00, -2.50800014E+00, -4.87800002E-01), _TMP18.xyz);
    _TMP42 = abs(_r0988);
    _r0998.x = dot(vec3( 1.43519993E+01, 2.81760006E+01, 5.47200012E+00), _TMP19.xyz);
    _r0998.y = dot(vec3( -1.18299997E+00, -2.31699991E+00, 3.49300003E+00), _TMP19.xyz);
    _r0998.z = dot(vec3( 2.99399996E+00, -2.50800014E+00, -4.87800002E-01), _TMP19.xyz);
    _TMP44 = abs(_r0998);
    _f4 = vec4(_TMP38.x, _TMP40.x, _TMP42.x, _TMP44.x);
    _fx = bvec4((vec4( 1.00000000E+00, -1.00000000E+00, -1.00000000E+00, 1.00000000E+00)*_fp.y + vec4( 1.00000000E+00, 1.00000000E+00, -1.00000000E+00, -1.00000000E+00)*_fp.x).x > 1.50000000E+00, (vec4( 1.00000000E+00, -1.00000000E+00, -1.00000000E+00, 1.00000000E+00)*_fp.y + vec4( 1.00000000E+00, 1.00000000E+00, -1.00000000E+00, -1.00000000E+00)*_fp.x).y > 5.00000000E-01, (vec4( 1.00000000E+00, -1.00000000E+00, -1.00000000E+00, 1.00000000E+00)*_fp.y + vec4( 1.00000000E+00, 1.00000000E+00, -1.00000000E+00, -1.00000000E+00)*_fp.x).z > -5.00000000E-01, (vec4( 1.00000000E+00, -1.00000000E+00, -1.00000000E+00, 1.00000000E+00)*_fp.y + vec4( 1.00000000E+00, 1.00000000E+00, -1.00000000E+00, -1.00000000E+00)*_fp.x).w > 5.00000000E-01);
    _fx_left = bvec4((vec4( 1.00000000E+00, -1.00000000E+00, -1.00000000E+00, 1.00000000E+00)*_fp.y + vec4( 5.00000000E-01, 2.00000000E+00, -5.00000000E-01, -2.00000000E+00)*_fp.x).x > 1.00000000E+00, (vec4( 1.00000000E+00, -1.00000000E+00, -1.00000000E+00, 1.00000000E+00)*_fp.y + vec4( 5.00000000E-01, 2.00000000E+00, -5.00000000E-01, -2.00000000E+00)*_fp.x).y > 1.00000000E+00, (vec4( 1.00000000E+00, -1.00000000E+00, -1.00000000E+00, 1.00000000E+00)*_fp.y + vec4( 5.00000000E-01, 2.00000000E+00, -5.00000000E-01, -2.00000000E+00)*_fp.x).z > -5.00000000E-01, (vec4( 1.00000000E+00, -1.00000000E+00, -1.00000000E+00, 1.00000000E+00)*_fp.y + vec4( 5.00000000E-01, 2.00000000E+00, -5.00000000E-01, -2.00000000E+00)*_fp.x).w > 0.00000000E+00);
    _fx_up = bvec4((vec4( 1.00000000E+00, -1.00000000E+00, -1.00000000E+00, 1.00000000E+00)*_fp.y + vec4( 2.00000000E+00, 5.00000000E-01, -2.00000000E+00, -5.00000000E-01)*_fp.x).x > 2.00000000E+00, (vec4( 1.00000000E+00, -1.00000000E+00, -1.00000000E+00, 1.00000000E+00)*_fp.y + vec4( 2.00000000E+00, 5.00000000E-01, -2.00000000E+00, -5.00000000E-01)*_fp.x).y > 0.00000000E+00, (vec4( 1.00000000E+00, -1.00000000E+00, -1.00000000E+00, 1.00000000E+00)*_fp.y + vec4( 2.00000000E+00, 5.00000000E-01, -2.00000000E+00, -5.00000000E-01)*_fp.x).z > -1.00000000E+00, (vec4( 1.00000000E+00, -1.00000000E+00, -1.00000000E+00, 1.00000000E+00)*_fp.y + vec4( 2.00000000E+00, 5.00000000E-01, -2.00000000E+00, -5.00000000E-01)*_fp.x).w > 5.00000000E-01);
    _interp_restriction_lv1 = bvec4(_e1.x != _f1.x && _e1.x != _h1.x, _e1.y != _f1.y && _e1.y != _h1.y, _e1.z != _f1.z && _e1.z != _h1.z, _e1.w != _f1.w && _e1.w != _h1.w);
    _interp_restriction_lv2_left = bvec4(_e1.x != _g1.x && _d2.x != _g1.x, _e1.y != _g1.y && _d2.y != _g1.y, _e1.z != _g1.z && _d2.z != _g1.z, _e1.w != _g1.w && _d2.w != _g1.w);
    _interp_restriction_lv2_up = bvec4(_e1.x != _c2.x && _b2.x != _c2.x, _e1.y != _c2.y && _b2.y != _c2.y, _e1.z != _c2.z && _b2.z != _c2.z, _e1.w != _c2.w && _b2.w != _c2.w);
    _a1012 = _e1 - _c2;
    _TMP1009 = abs(_a1012);
    _a1016 = _e1 - _g1;
    _TMP1013 = abs(_a1016);
    _a1020 = _i - _h5;
    _TMP1017 = abs(_a1020);
    _a1024 = _i - _f4;
    _TMP1021 = abs(_a1024);
    _a1028 = _h1 - _f1;
    _TMP1025 = abs(_a1028);
    _TMP21 = _TMP1009 + _TMP1013 + _TMP1017 + _TMP1021 + 4.00000000E+00*_TMP1025;
    _a1034 = _h1 - _d2;
    _TMP1031 = abs(_a1034);
    _a1038 = _h1 - _i5;
    _TMP1035 = abs(_a1038);
    _a1042 = _f1 - _i4;
    _TMP1039 = abs(_a1042);
    _a1046 = _f1 - _b2;
    _TMP1043 = abs(_a1046);
    _a1050 = _e1 - _i;
    _TMP1047 = abs(_a1050);
    _TMP22 = _TMP1031 + _TMP1035 + _TMP1039 + _TMP1043 + 4.00000000E+00*_TMP1047;
    _edr = bvec4(_TMP21.x < _TMP22.x && _interp_restriction_lv1.x, _TMP21.y < _TMP22.y && _interp_restriction_lv1.y, _TMP21.z < _TMP22.z && _interp_restriction_lv1.z, _TMP21.w < _TMP22.w && _interp_restriction_lv1.w);
    _a1054 = _f1 - _g1;
    _TMP1051 = abs(_a1054);
    _a1058 = _h1 - _c2;
    _TMP1055 = abs(_a1058);
    _edr_left = bvec4((2.00000000E+00*_TMP1051).x <= _TMP1055.x && _interp_restriction_lv2_left.x, (2.00000000E+00*_TMP1051).y <= _TMP1055.y && _interp_restriction_lv2_left.y, (2.00000000E+00*_TMP1051).z <= _TMP1055.z && _interp_restriction_lv2_left.z, (2.00000000E+00*_TMP1051).w <= _TMP1055.w && _interp_restriction_lv2_left.w);
    _a1062 = _f1 - _g1;
    _TMP1059 = abs(_a1062);
    _a1066 = _h1 - _c2;
    _TMP1063 = abs(_a1066);
    _edr_up = bvec4(_TMP1059.x >= (2.00000000E+00*_TMP1063).x && _interp_restriction_lv2_up.x, _TMP1059.y >= (2.00000000E+00*_TMP1063).y && _interp_restriction_lv2_up.y, _TMP1059.z >= (2.00000000E+00*_TMP1063).z && _interp_restriction_lv2_up.z, _TMP1059.w >= (2.00000000E+00*_TMP1063).w && _interp_restriction_lv2_up.w);
    _nc = bvec4(_edr.x && (_fx.x || _edr_left.x && _fx_left.x || _edr_up.x && _fx_up.x), _edr.y && (_fx.y || _edr_left.y && _fx_left.y || _edr_up.y && _fx_up.y), _edr.z && (_fx.z || _edr_left.z && _fx_left.z || _edr_up.z && _fx_up.z), _edr.w && (_fx.w || _edr_left.w && _fx_left.w || _edr_up.w && _fx_up.w));
    _a1070 = _e1 - _f1;
    _TMP1067 = abs(_a1070);
    _a1074 = _e1 - _h1;
    _TMP1071 = abs(_a1074);
    _px = bvec4(_TMP1067.x <= _TMP1071.x, _TMP1067.y <= _TMP1071.y, _TMP1067.z <= _TMP1071.z, _TMP1067.w <= _TMP1071.w);
    if (_nc.x) { 
        if (_px.x) { 
            _TMP30 = _TMP5.xyz;
        } else {
            _TMP30 = _TMP7.xyz;
        } 
        _TMP29 = _TMP30;
    } else {
        if (_nc.y) { 
            if (_px.y) { 
                _TMP32 = _TMP1.xyz;
            } else {
                _TMP32 = _TMP5.xyz;
            } 
            _TMP31 = _TMP32;
        } else {
            if (_nc.z) { 
                if (_px.z) { 
                    _TMP34 = _TMP3.xyz;
                } else {
                    _TMP34 = _TMP1.xyz;
                } 
                _TMP33 = _TMP34;
            } else {
                if (_nc.w) { 
                    if (_px.w) { 
                        _TMP36 = _TMP7.xyz;
                    } else {
                        _TMP36 = _TMP3.xyz;
                    } 
                    _TMP35 = _TMP36;
                } else {
                    _TMP35 = _TMP4.xyz;
                } 
                _TMP33 = _TMP35;
            } 
            _TMP31 = _TMP33;
        } 
        _TMP29 = _TMP31;
    } 
    _ret_0 = vec4(_TMP29.x, _TMP29.y, _TMP29.z, 1.00000000E+00);
    FragColor = _ret_0;
    return;
} 
#endif
