#!/bin/sh

### BEGIN INIT INFO
# Provides:          asplashscreen
# Required-Start:    mountdevsubfs
# Required-Stop:
# Default-Start:     S
# X-Start-Before:    checkroot
# Default-Stop:
# Short-Description: Show custom splashscreen
# Description:       Show custom splashscreen
### END INIT INFO

ROOTDIR="/opt/retropie"
DATADIR="/home/pi/RetroPie"
RANDOMIZE="disabled"
REGEX_VIDEO="\.avi\|\.mov\|\.mp4\|\.mkv\|\.3gp\|\.mpg\|\.mp3\|\.wav\|\.m4a\|\.aac\|\.ogg\|\.flac"
REGEX_IMAGE="\.bmp\|\.jpg\|\.jpeg\|\.gif\|\.png\|\.ppm\|\.tiff\|\.webp"

do_start () {
 local config="/etc/splashscreen.list"
 local music="/etc/music.list"
 local line
 line="$(cat "$config" | shuf -n1)"
if $(echo "$line" | grep -q "$REGEX_VIDEO"); then
  mpv -fs -vo sdl "$line" 
 elif $(echo "$line" | grep -q "$REGEX_IMAGE"); then
fbi -T 2 -once -noverbose -a "$line" >/dev/null 2>&1
local musiclist="$(cat "$music" | shuf -n1)"
mpv "$musiclist"
fi
exit 0
}

case "$1" in
    start|"")
        do_start &
        ;;
    restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
       ;;
    stop)
        # No-op
        ;;
    status)
        exit 0
        ;;
    *)
        echo "Usage: asplashscreen [start|stop]" >&2
        exit 3
        ;;
esac

:
