#! /bin/sh
### BEGIN INIT INFO
# Provides:          asplashscreen
# Required-Start:
# Required-Stop:
# Default-Start:     S
# Default-Stop:
# Short-Description: Show custom splashscreen
# Description:       Show custom splashscreen
### END INIT INFO

do_start () {

    while read splashline; do
        echo Playing splash video or image $splashline
        isMovie=$(echo $splashline | grep -o ".mov\|.mp4\|.mkv\|.3gp\|.mpg")
        if [ -z "$isMovie" ]; then
            /usr/bin/fbi -T 1 -once -t 10 -noverbose -a $splashline
            sleep 12
        else
            mplayer $splashline
        fi
    done </etc/splashscreen.list
    exit 0
}

case "$1" in
  start|"")
    do_start &
    ;;
  restart|reload|force-reload)
    echo "Error: argument '$1' not supported" >&2
    exit 3
    ;;
  stop)
    # No-op
    ;;
  status)
    exit 0
    ;;
  *)
    echo "Usage: asplashscreen [start|stop]" >&2
    exit 3
    ;;
esac

:
