#! /bin/sh
### BEGIN INIT INFO
# Provides:          asplashscreen
# Required-Start:
# Required-Stop:
# Should-Start:      
# Default-Start:     S
# Default-Stop:
# Short-Description: Show custom splashscreen
# Description:       Show custom splashscreen
### END INIT INFO


do_start () {

    line=$(head -n 1 /etc/splashscreen.list)
    isMovie=$(echo $line | grep -o "*.mpg")
    if [ -z "$isMovie" ]; then
      /usr/bin/fbi -T 1 -noverbose -a -l /etc/splashscreen.list &
    else
      mplayer $line &
    fi
    exit 0
}

case "$1" in
  start|"")
    do_start
    ;;
  restart|reload|force-reload)
    echo "Error: argument '$1' not supported" >&2
    exit 3
    ;;
  stop)
    # No-op
    ;;
  status)
    exit 0
    ;;
  *)
    echo "Usage: asplashscreen [start|stop]" >&2
    exit 3
    ;;
esac

: