#!/bin/bash -ue
# Sync ROMS from external drive
# Christian Bryn <chr.bryn@gmail.com> 2013
# Florian Mueller <contact@petrockblock.com> 2015

## config / defaults
user="USERTOBECHOSEN"

home="$(eval echo ~$user)"
retropie_path="$home/RetroPie"
retropie_path_roms="$retropie_path/roms"
retropie_path_emulationstation="$home/.emulationstation"

usb_path="$UM_MOUNTPOINT/retropie"
usb_path_roms="$usb_path/roms"
usb_path_emulationstation_fromrpi="$usb_path/emulationstation/fromRPi"
usb_path_emulationstation_torpi="$usb_path/emulationstation/toRPi"

## internals
hook_name=${0##*/}

## functions
function log() {
    logger -p user.$1 -t usbmount-"$hook_name"-[$$] -- "$2"
}

## some sanity checking
if [[ -z "$UM_MOUNTPOINT" ]]; then
    log err "UM_MOUNTPOINT not set!"
    exit 0;
fi

if [[ ! -d "$UM_MOUNTPOINT" ]]; then
    log err "UM_MOUNTPOINT is not a directory"
    exit 0;
fi

# make sure we have something to sync from
if [[ ! -d "$usb_path" ]]; then
    exit 0
fi

## main
# mirror romdir structure to external drive
if [[ ! -d "$usb_path_roms" ]]; then
    log info "Attempting to create directory structure for ROMS in '$usb_path_roms' ..."
    # fetch list of romdirs from current installation and mirror onto external driv
    find "$retropie_path"/roms -mindepth 1 -maxdepth 1 -type d -printf "$usb_path_roms/%f\n" | xargs mkdir -p 2>/dev/null || true
    exit 0
fi

# make folders for config syncing
mkdir -p "$usb_path_emulationstation_fromrpi" "$usb_path_emulationstation_torpi"

# copy ROMs from USB stick to local SD card
rsync -au --exclude '._*' --max-delete=-1 "$usb_path_roms/" "$retropie_path_roms/" >/dev/null 2>&1 || log err "rsync failed to sync ROMS, returned error code $?"

# copy EmulationStation configuration to USB stick 
rsync -au --exclude '._*' --max-delete=-1 "$retropie_path_emulationstation/" "$usb_path_emulationstation_fromrpi/" >/dev/null 2>&1 || log err "rsync failed to sync EMULATIONSTATION configuration, returned error code $?"

# copy EmulationStation configuration from USB stick to local SD card
rsync -au --exclude '._*' --max-delete=-1 "$usb_path_emulationstation_torpi/" "$retropie_path_emulationstation/" >/dev/null 2>&1 || log err "rsync failed to sync EMULATIONSTATION configuration, returned error code $?"

# make sure that user can access the files
chown -R $user:$user "$retropie_path" "$retropie_path_emulationstation"

# unmount USB stick
umount "$UM_MOUNTPOINT"
