#!/bin/bash

filelist=()

# theme.xml files, show with find ./RetroPie/roms -type f -name "*.xml" ! -name "gamelist.xml"
filelist+=("./RetroPie/roms/neogeo/theme.xml")
filelist+=("./RetroPie/roms/gamegear/theme.xml")
filelist+=("./RetroPie/roms/psx/theme.xml")
filelist+=("./RetroPie/roms/mastersystem/theme.xml")
filelist+=("./RetroPie/roms/ngpc/theme.xml")
filelist+=("./RetroPie/roms/atari2600/theme.xml")
filelist+=("./RetroPie/roms/gba/theme.xml")
filelist+=("./RetroPie/roms/pcengine/theme.xml")
filelist+=("./RetroPie/roms/amiga/theme.xml")
filelist+=("./RetroPie/roms/snes/theme.xml")
filelist+=("./RetroPie/roms/gbc/theme.xml")
filelist+=("./RetroPie/roms/megadrive/theme.xml")
filelist+=("./RetroPie/roms/nes/theme.xml")
filelist+=("./RetroPie/roms/gb/theme.xml")
filelist+=("./RetroPie/roms/doom/theme.xml")
filelist+=("./RetroPie/roms/eduke32/theme.xml")
filelist+=("./RetroPie/roms/mame/theme.xml")
filelist+=("./RetroPie/roms/scummvm/theme.xml")
filelist+=("./RetroPie/roms/zxspectrum/theme.xml")


# art and sound files, show with find ./.emulationstation/themes -type f -name "*.jpg" -o -name "*.png" -o -name "*.wav"
filelist+=("./.emulationstation/themes/general_art/darkgrey.png")
filelist+=("./.emulationstation/themes/general_art/RetroPieProjectLogoSmallGrey.png")
filelist+=("./.emulationstation/themes/general_art/grey.png")
filelist+=("./.emulationstation/themes/general_art/blue.png")
filelist+=("./.emulationstation/themes/general_art/lightred.png")
filelist+=("./.emulationstation/themes/general_art/green.png")
filelist+=("./.emulationstation/themes/general_art/blue2.png")
filelist+=("./.emulationstation/themes/general_art/blue3.png")
filelist+=("./.emulationstation/themes/general_art/orange.png")
filelist+=("./.emulationstation/themes/atari2600_art/GS25.wav")
filelist+=("./.emulationstation/themes/atari2600_art/RetroPieProjectLogoSmallGrey.png")
filelist+=("./.emulationstation/themes/atari2600_art/atari_logo.png")
filelist+=("./.emulationstation/themes/atari2600_art/atari_blue.png")
filelist+=("./.emulationstation/themes/atari2600_art/atari_grey.png")
filelist+=("./.emulationstation/themes/atari2600_art/GS42.wav")
filelist+=("./.emulationstation/themes/atari2600_art/atari_case.png")
filelist+=("./.emulationstation/themes/atari2600_art/GS28.wav")
filelist+=("./.emulationstation/themes/atari2600_art/SNES5.wav")
filelist+=("./.emulationstation/themes/atari2600_art/atari_divider.png")
filelist+=("./.emulationstation/themes/scummvm_art/scummvm_logo.png")
filelist+=("./.emulationstation/themes/scummvm_art/scummvm_art2.png")
filelist+=("./.emulationstation/themes/scummvm_art/scummvm_art1.png")
filelist+=("./.emulationstation/themes/sounds/GS25.wav")
filelist+=("./.emulationstation/themes/sounds/GS42.wav")
filelist+=("./.emulationstation/themes/sounds/GS28.wav")
filelist+=("./.emulationstation/themes/sounds/SNES5.wav")
filelist+=("./.emulationstation/themes/psx_art/psx_logo.png")
filelist+=("./.emulationstation/themes/psx_art/psx_bg.jpg")
filelist+=("./.emulationstation/themes/psx_art/psx_divider.png")
filelist+=("./.emulationstation/themes/pcengine_art/pcengine_art1.png")
filelist+=("./.emulationstation/themes/pcengine_art/pcengine_case.png")
filelist+=("./.emulationstation/themes/pcengine_art/pcengine_logo.png")
filelist+=("./.emulationstation/themes/intellivision_art/intellivision_art1.png")
filelist+=("./.emulationstation/themes/intellivision_art/intellivision_case.png")
filelist+=("./.emulationstation/themes/intellivision_art/intellivision_logo.png")
filelist+=("./.emulationstation/themes/snes_art/snes_logo.png")
filelist+=("./.emulationstation/themes/snes_art/snes_bg.png")
filelist+=("./.emulationstation/themes/snes_art/snes_bg_grey.jpg")
filelist+=("./.emulationstation/themes/mame_art/mame_logo.jpg")
filelist+=("./.emulationstation/themes/mame_art/mame_bg.jpg")
filelist+=("./.emulationstation/themes/mame_art/mame_bg_black.jpg")
filelist+=("./.emulationstation/themes/zxspectrum_art/zxspectrum_art1.png")
filelist+=("./.emulationstation/themes/zxspectrum_art/zxspectrum_logo.png")
filelist+=("./.emulationstation/themes/zxspectrum_art/zxspectrum_case.png")
filelist+=("./.emulationstation/themes/dos_art/dos_logo.png")
filelist+=("./.emulationstation/themes/dos_art/dos_art1.png")
filelist+=("./.emulationstation/themes/dos_art/dos_art2.png")
filelist+=("./.emulationstation/themes/nes_art/nes_logo.png")
filelist+=("./.emulationstation/themes/nes_art/nes_bg_grey.jpg")
filelist+=("./.emulationstation/themes/nes_art/nes_bg_stripes.png")
filelist+=("./.emulationstation/themes/gbc_art/gbc_logo.png")
filelist+=("./.emulationstation/themes/gbc_art/plastic_glare.png")
filelist+=("./.emulationstation/themes/gbc_art/gbc_bg.jpg")
filelist+=("./.emulationstation/themes/gba_art/gba_logo.png")
filelist+=("./.emulationstation/themes/gba_art/shadow.png")
filelist+=("./.emulationstation/themes/gba_art/gba_bg_left.jpg")
filelist+=("./.emulationstation/themes/gba_art/gba_bg_stripes.png")
filelist+=("./.emulationstation/themes/doom_art/doom_art.png")
filelist+=("./.emulationstation/themes/doom_art/doom_logo.png")
filelist+=("./.emulationstation/themes/ngpc_art/ngpc_logo.png")
filelist+=("./.emulationstation/themes/ngpc_art/ngpc_bg.jpg")
filelist+=("./.emulationstation/themes/gb_art/gb_bg.png")
filelist+=("./.emulationstation/themes/gb_art/gb_logo.png")
filelist+=("./.emulationstation/themes/neogeo_art/neogeo_divider.png")
filelist+=("./.emulationstation/themes/neogeo_art/neogeo_logo.png")
filelist+=("./.emulationstation/themes/neogeo_art/neogeo_bg.jpg")
filelist+=("./.emulationstation/themes/mastersystem_art/mastersystem_bg.png")
filelist+=("./.emulationstation/themes/mastersystem_art/mastersystem_logo.png")
filelist+=("./.emulationstation/themes/gamegear_art/sgg_logo.png")
filelist+=("./.emulationstation/themes/gamegear_art/sgg_bg_pink_stripes.png")
filelist+=("./.emulationstation/themes/gamegear_art/divider.png")
filelist+=("./.emulationstation/themes/gamegear_art/sgg_bg_dark_stripes.png")
filelist+=("./.emulationstation/themes/amiga_art/amiga_case.png")
filelist+=("./.emulationstation/themes/amiga_art/amiga_art1.png")
filelist+=("./.emulationstation/themes/amiga_art/amiga_logo.png")
filelist+=("./.emulationstation/themes/amiga_art/amiga_art2.png")
filelist+=("./.emulationstation/themes/megadrive_art/megadrive_bg_dark_stripes.png")
filelist+=("./.emulationstation/themes/megadrive_art/megadrive_bg_red_stripes.png")
filelist+=("./.emulationstation/themes/megadrive_art/megadrive_top_bg.png")
filelist+=("./.emulationstation/themes/megadrive_art/divider.png")
filelist+=("./.emulationstation/themes/megadrive_art/megadrive_logo.png")
filelist+=("./.emulationstation/themes/duke3d_art/duke3d_artwork1.png")

tar -c -vf RetroPieSetupThemes_`date +%d%m%y`.tar ${filelist[0]}

tLen=${#filelist[@]}
for (( i=1; i<${tLen}; i++ ));
do
	tar -r -vf RetroPieSetupThemes_`date +%d%m%y`.tar ${filelist[$i]}
done

if [[ -f RetroPieSetupThemes_`date +%d%m%y`.tar.bz2 ]]; then
	rm RetroPieSetupThemes_`date +%d%m%y`.tar.bz2
fi
bzip2 RetroPieSetupThemes_`date +%d%m%y`.tar

echo "Done."
