#!/bin/bash
# this script is used by lr-mess to run softwares without using softlists.

if [ $# -lt 6 ]; then
	echo "usage: $0 <path/to/retroarch_binary> </path/to/mess_libretro> </path/to/retroarch.cfg> <system_name> </path/to/bios_folder> <further parameters|path/to/game_to_launch>"
	exit 1
fi


_retroarchbin="$1"
_messpath="$2"
_config="$3"
_system="$4"
_biosdir="$5"

echo "[.] parameters dump"
echo "\t_retroarchbin: $_retroarchbin"
echo "\t_messpath: $_messpath"
echo "\t_config: $_config (+ $_config.add)"
echo "\t_system: $_system"
echo "\t_biosdir: $_biosdir"

# generate parameters for mess.cmd
_cmdarr=()
_cmdarr+=( "$_system" )
_cmdarr+=( "-rp" )
_cmdarr+=( "$_biosdir" )
_count=0
_stopadd=false
for _param in "$@"; do
    if [ $_count -gt 4 ]; then
		# we need to strip --appendconfig here, which seems to be added by emulationstation in the end......
		# we also remove verbose, in case it's launched with verbose on from runcommand.sh (we use --verbose anyway ourself)
		if [ "$_param" = "--appendconfig" ] || [ "$_param" = "--verbose" ]; then
			_stopadd=true
		fi
		if [ "$_stopadd" = false ]; then
	        _cmdarr+=( \""$_param"\" )
		fi
    fi
    ((_count+=1))
done

# generate /tmp/mess.cmd
echo "\t/tmp/mess.cmd content: ${_cmdarr[@]}"
rm /tmp/mess.cmd
rm /tmp/config.add
echo "${_cmdarr[@]}" > /tmp/mess.cmd

# run retroarch & mess using the custom generated launcher cmd
# $_config.add has been generated by the setup script, it's needed to force softlists disabled...
# we also add here the same /dev/shm/retroarch.cfg that was stripped above....
cat /dev/shm/retroarch.cfg >> /tmp/config.add
cat "$_config.add" >> /tmp/config.add
set -- "$_retroarchbin"
set -- "$@" --verbose --config "$_config" --appendconfig /tmp/config.add -L "$_messpath" /tmp/mess.cmd
echo "[.] launching: $@"

"$@"

# deleting tmp 
#rm /tmp/mess.cmd

